backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "staff"
    label: "Staff Members"
    folder: "content/staff"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Photo", name: "photo_url", widget: "image", default: "img/staff/placeholder.jpg"}
      - {label: "Type", name: "type", widget: "select", options: ["teacher", "board"]}
      - {label: "Order", name: "order", widget: "number", default: 0}

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["News", "Events", "Student Achievements", "Educational Insights", "Community Updates"]}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
